export { default as AuthPage } from './AuthPage'
export { default as HomePage } from './HomePage'
export { default as NewTaskPage } from './NewTaskPage'
export { default as RegisterPage } from './RegisterPage'
export { default as ServerPage } from './ServerPage'
export { default as TasksPage } from './TasksPage'
export * from './index'
